import React from 'react';
import Bloger from '@/layouts/Bloger';

export const metadata = {
    title: 'Blog',
    description: 'Generated by create next app',
}

const page = () => {
    return (
        <div className='maxWidth1400px'>
           <Bloger/>
        </div>
    );
};

export default page;