export const metadata = {
    title: 'Calligraphy',
    description: 'Generated by create next app',
  }
  
  export default function CartLayout({ children }) {
    return (
      <>
          {children}
      </>
    )
  }
  