export const metadata = {
    title: 'Comic',
    description: 'Generated by create next app',
}

export default function CartLayout({ children }) {
    return (
        <>
            {children}
        </>
    )
}
  